### PR TITLE
Feature/bare tabs

### PR DESCRIPTION
**Pull request by arcpato**
- Adding property bare to px-tab-set to allow users to specify the tabs style. 

Default:  `<px-tab-set ...></px-tab-set>`

screen shot 2016-05-03 at 3 43 33 pm

New config option:  `<px-tab-set bare...></px-tab-set>`
screen shot 2016-05-03 at 3 45 04 pm
- Included tests for tabs with bare property enabled

### CODE REVIEW

**Comment by mdwragg** [comment]
Hi @arcpato - thanks for the PR! Sadly the tests are failing on Firefox (see above). Can you take a look and get them up and running? I'm on vacation but will assign a couple of people to look at your PR once they're passing in Travis and Sauce.

Thanks!

**Comment by mdwragg** [comment]
Ah, can only assign one person... @benoitjchevalier @runn-vermel @gedesigntech - can one of you take a look at this once the tests pass? Thanks. Might need to go in front of the designers too - not sure if @arcpato reviewed it with our designers or not...

**Comment by mdwragg** [comment]
image

Hope you don't find the process to be like this Angelica :-)

**Comment by arcpato** [comment]
I kinda am hating it. :)

**Comment by runn-vermel** [comment]
@arcpato - Let me know when the tests pass and i'll put this in front of our designers, Angelica.

**Comment by arcpato** [comment]
@runn-vermel I think it is good for review now. Sirisha helped me figure out what was off in the tests (thanks!)

I talked to Hans about this change (which is also why it is not replacing the original styles, but providing an alternative style that can be enabled). Feel free to show/vet with him and the other designers.

**Comment by runn-vermel** [comment]
Design (Hans) signed off on this, code looks good :)

**Pull request merged**
